### ISSUE TITLE
Unknown use case for timestamps in cells CZ1:DB2

### ISSUE THREAD

**Issue by just-Addict** [collin-li/pokemon-go-iv-calculator#5]
What are the cells CZ1:DB2 supposed to do?

For the life of me I can't seem to figure what the purpose is... what do I enter in Cell DO1? 
It is formatted as a date/time field but no matter what I put in, the result don't make sense to me.

**Comment by collin-li** [comment]
CZ1:DB2 help you with your Lucky Egg timing.

It's designed so you put in your start time in the top-left, and then it actively tracks how many have you evolved in the time elapsed to NOW() and how many you will have left at your current evolve rate. It's a very low-value feature that I left in without explaining.

The way it picks up on evolved Pokemon is through the comments field - you need to write "EVOLVED" in it for it to pick up that you've evolved something.

**Comment by just-Addict** [comment]
Ah so that's why I couldn't figure their purpose. 
For some strange reason CZ1 never updates to the current time even though it is still before the calculated end time in DB1
It does update if I just put NOW() in CZ1 but not when it's part of a formula.

However, it doesn't show me how many I have left, for that it would need a count of how many I plan to evolve, not? DA2 does show me the EVOLVED count, but CZ2 always stays zero resulting in DB2 just showing the negative value of DA2.

**Comment by collin-li** [comment]
To clarify the purpose of each cell:
- **CZ1**: The earlier time out of: (i) the current time, or (ii) cell DA1 + 30 minutes (for the most part, this is a cell for intermediate calculations, to avoid having a super complicated formula I wouldn't remember how I built in cell CZ2)
- **DA1**: The start time of the Lucky Egg (you should write =NOW() into this, then copy and re-paste it as values over the same cell to get Excel to give you a properly formatted time-stamp of the current time: I tend to do this right before I trigger my Lucky Egg, and in between the 1st evolution animation I will go back and correct the exact timing to the second - I am also watching a clock for the seconds when I press 'go' on the Lucky Egg)
- **DB1**: The end time of the Lucky egg
- **CZ2**: Projected number of total "EVOLVED" based on your current pace
- **DA2**: Number of actual "EVOLVED"
- **DB2**: How many more evolves you should be able to fit in, based on current pace

Note that this simple extrapolation calculation is going to underestimate your evolves if you do 2 evolves on one Pokemon (the spreadsheet doesn't have that nuance), and/or if there are new Pokedex entries **earlier in your batch**. This is because it is extrapolating on your current batch, as opposed to using any set pace that most evolve calculators use.

For the most part, this is a minor feature that I built for myself, and there are many other Lucky Egg calculators out there that you may already be used to, and there is no real benefit in using the one integrated into the spreadsheet vs. those ones.

(Apologies for the late reply!)
